version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amsdb
      MYSQL_USER: amsuser
      MYSQL_PASSWORD: amspass
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    depends_on:
      - mysql

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    restart: always
    ports:
      - "8086:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/amsdb
      SPRING_DATASOURCE_USERNAME: amsuser
      SPRING_DATASOURCE_PASSWORD: amspass
    depends_on:
      - mysql

volumes:
  mysql_data:
